function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(cents){return new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2}).format(cents/100)}
function form(action,fields,button,encoding=''){return `<form action="${esc(action)}" method="post" ${encoding?`enctype="${encoding}"`:''}>${fields}<button>${esc(button)}</button></form>`}
function card(p,user,detail=false){return `<article class="product-card"><a class="product-image" href="/product/${esc(p.slug)}"><img src="${p.image?'/public/uploads/'+encodeURIComponent(p.image):'/public/no_image.png'}" alt="${esc(p.name)}" onerror="this.onerror=null;this.src='/public/no_image.png'"></a><div class="product-info"><span class="eyebrow">${esc(p.category||'КОЛЛЕКЦИЯ')}</span>${detail?'':`<h3><a href="/product/${esc(p.slug)}">${esc(p.name)}</a></h3>`}<div class="product-footer"><strong>${money(p.price)}</strong><span>${p.stock?'В наличии':'Нет в наличии'}</span></div><div class="product-actions">${p.stock?form(`/cart/add/${p.id}`,'','В корзину'):''}${user?form(`/wishlist/${p.id}`,'','♡'):''}</div></div></article>`}
function layout(title,content,user,notice,count){return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Forma</title><link rel="stylesheet" href="/public/style.css"><script src="/public/app.js" defer></script></head><body><header class="site-header"><div class="shell nav"><a class="logo" href="/">FORMA<span>.</span></a><nav aria-label="Основная навигация"><a href="/">Каталог</a><a href="/cart">Корзина <span class="count">${count}</span></a>${user?`<a href="/wishlist">Избранное</a><a href="/profile">Кабинет</a>${user.role==='admin'?'<a href="/admin">Админ</a>':''}<form action="/logout" method="post"><button class="text-button">Выйти</button></form>`:'<a href="/login">Войти</a>'}</nav></div></header><main class="shell">${notice?`<div class="notice" role="status">${esc(notice)}</div>`:''}${content}</main><footer class="shell footer"><strong>FORMA.</strong><span>Продуманная мебель для реальной жизни.</span><span>Prac4 · Node.js / Express</span></footer></body></html>`}
module.exports={esc,money,form,card,layout};



